create table users
(
    height          double precision not null,
    id              integer generated by default as identity
        primary key,
    is_activated    boolean,
    weight          double precision not null,
    email           varchar(255),
    gender          varchar(255)
        constraint users_gender_check
            check ((gender)::text = ANY ((ARRAY ['MALE'::character varying, 'FEMALE'::character varying])::text[])),
    password        varchar(255),
    role            varchar(255)
        constraint users_role_check
            check ((role)::text = ANY ((ARRAY ['USER'::character varying, 'ADMIN'::character varying])::text[])),
    username        varchar(255),
    last_check_time timestamp(6)
);

alter table users
    owner to postgres;

