create table user_activatecode
(
    id              integer generated by default as identity
        constraint user_activatecode_pk
            primary key,
    user_id         integer
        constraint user_activatecode_users_id_fk
            references users,
    activation_code integer
);

alter table user_activatecode
    owner to postgres;

