create table user_history
(
    burned_calories double precision,
    duration        double precision,
    exercise_id     integer
        constraint fkeirsutfomn0ldcu4cjnbxksar
            references exercises,
    id              integer generated by default as identity
        primary key,
    user_id         integer
        constraint fkd8f7md75uuycl5mgtl394nqoi
            references users,
    time            timestamp(6)
);

alter table user_history
    owner to postgres;

